name: ProjectCosmos
main: com.xoarasol.projectcosmos.ProjectCosmos
version: 2.0
authors: [ 'Wilson & XoaraSol' ]
depend: [ 'ProjectKorra' ]
api-version: 1.21.4
permissions:
  bending.cosmic:
    default: true
    description: Grants access to all Cosmicbending abilities.
    children:
      bending.cosmic.gravitybending: true
      bending.cosmic.darkcosmicbending: false
      bending.cosmic.lunarbending: true
      bending.cosmic.solarbending: true
      bending.cosmic.combos: true
      bending.cosmic.passive: true
      bending.ability.accretiondisk: true
      bending.ability.blackhole: true
      bending.ability.stellarcrash: true
      bending.ability.tectonicdisruption: true
      bending.ability.defiance: true
      bending.ability.blastoff: true
      bending.ability.gravitybinding: true
      bending.ability.gravitymanipulation: true
      bending.ability.massmanipulation: true
      bending.ability.lunarclap: true
      bending.ability.lunarglint: true
      bending.ability.moonfall: true
      bending.ability.orbital: true
      bending.ability.rover: true
      bending.ability.crackofdawn: true
      bending.ability.pulsar: true
      bending.ability.solarcyclone: true
      bending.ability.astralflight: true
      bending.ability.constellationcutter: true
      bending.ability.cosmicblast: true
      bending.ability.cosmicseeker: true
      bending.ability.eventhorizon: true
      bending.ability.galacticripple: true
      bending.ability.spacewarp: true
      bending.ability.starsurge: true
      bending.ability.stellarbreath: true
      bending.ability.supernova: true
      bending.ability.theskiesdescend: true
      bending.ability.wormhole: true

